### ISSUE TITLE
Better account storing ?

### ISSUE THREAD

**Issue by gand-elf13** [leonardo-racic/fish-a-fiche#1]
I think it would be usefull to associate each entry in the account.json with an id so account with same pseudo would be easier to identify 

Will work on it once i get back (exept if this is not accepted)

**Comment by leonardo-racic** [comment]
I agree, I've done a draft of a better account data json storing. I just need to apply it, after we all validate it, so it's still a wip

**Comment by leonardo-racic** [comment]
This has been corrected. We now use token in the servers to handle accounts. The profile url however contains a hashed version of the token to avoid token leaking potentially leading to identity theft.
Thank you for your suggestions! ^^
