### ISSUE TITLE
bug d'affichage avec nom de cheat-sheet long et "pieges"

### ISSUE THREAD

**Issue by gand-elf13** [leonardo-racic/fish-a-fiche#9]
j'ai fait un petit peu de brute force sur le site pour verifier qu'il n'y as pas de grosses failles des securites, il n'y en as pas d'evidentes. cependat si on met des nom de cheat-sheet bizarre (type injection SQL) l'affichage sut le search engine et sur le profile est bugge (alonge et beaucoup trop de cheat-sheet par ligne)

**Comment by leonardo-racic** [comment]
Peux-tu me montrer irl ou un screenshot de cette situation?

**Comment by leonardo-racic** [comment]
I changed it today, it should be good
